version: '3.1'

services:
 db:
  image: postgres:16-alpine
  restart: always
  environment:
   - POSTGRES_PASSWORD=password
  volumes:
   - ./data.sql:/script.sql
   - ./schema.sql:/schema.sql
   - /postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: {}
  